### ISSUE TITLE
Approach - recreating the layout vs. embedding

### ISSUE THREAD

**Issue by dandv** [abraham/twitter-status#75]
Thanks for making this available as a web component and not succumbing to picking a framework over another.

Would it help to document how this differs from using Twitter's [oEmbed API](https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview.html)? Seems like the component does a lot of work to replicate what [others do by simply using that API](https://github.com/capaj/react-tweet-embed) and including the `//platform.twitter.com/widgets.js` script, and that comes with a loss of fidelity, and issues like #74. A comparison with using the embedding API would be great. Thanks!

**Comment by abraham** [comment]
@dandv does #80 cover everything you were thinking? Anything else that should be added?

**Comment by dandv** [comment]
Excellent, thank you very much! I wish more developers [addressed prior art](https://github.com/search?q=comparison+with+author%3Adandv&ref=searchresults&type=Issues&utf8=✓) in their libraries.
